apps/courses/urls.py
#!/usr/bin/env python3
# --*-- coding: utf-8 --*--
"""
    Time    : 2018/4/15 16:18
    Author  : LeeLong
    File    : urls.py
    Software: PyCharm
    Description:
"""


from django.conf.urls import url

from .views import CourseHomeView, CourseDetailView, CourseVideoView, CourseCommentView, AddCommentView

urlpatterns = [
    url(r'^list/$', CourseHomeView.as_view(), name='course_home'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^video/(?P<course_id>\d+)/$', CourseVideoView.as_view(), name='course_video'),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    url(r'^addcomment/$', AddCommentView.as_view(), name='add_comment'),
    # url(r'^tlist/$', TeacherListView.as_view(), name='teacher_list'),

]

apps/organization/urls.py
#!/usr/bin/env python3
# --*-- coding: utf-8 --*--
"""
    Time    : 2018/4/14 18:29
    Author  : LeeLong
    File    : urls.py
    Software: PyCharm
    Description:
"""
from django.conf.urls import url

from .views import OrgListView, UserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeachView, OrgUserFavoriteView,\
    TeacherListView

urlpatterns = [
    # 机构列表首页
    url(r'^list/$', OrgListView.as_view(), name='org_list'),
    # 用户咨询表单
    url(r'^userask/$', UserAskView.as_view(), name='user_ask'),
    # 机构首页
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    # 机构课程页
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    # 机构描述页
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    # 机构讲师页
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeachView.as_view(), name='org_teach'),
    # 用户机构收藏处理功能
    url(r'^favorite/$', OrgUserFavoriteView.as_view(), name='favorite'),

    # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
]

apps/users/urls.py
#!/usr/bin/env python3
# --*-- coding: utf-8 --*--
"""
    Time    : 2018/4/18 11:24
    Author  : LeeLong
    File    : urls.py
    Software: PyCharm
    Description:
"""
from django.conf.urls import url

from .views import UserCenterView, UserCenterMyCourseView, UserCenterMessageView, UserCenterFavCourseView,\
    SendEmailCodeView, UpdateEmailView, UploadImageView, UpdatePwdView, UserCenterFavOrgView, UserCenterFavTeacherView

urlpatterns = [
    # 个人信息主页
    url(r'^info/$', UserCenterView.as_view(), name='user_center'),

    # 个人课程
    url(r'^course/$', UserCenterMyCourseView.as_view(), name='user_course'),

    # 消息页面
    url(r'^message/$', UserCenterMessageView.as_view(), name='user_message'),

    # 收藏课程
    url(r'^fav/course/$', UserCenterFavCourseView.as_view(), name='user_fav_course'),

    # 课程机构收藏
    url(r'^fav/org/$', UserCenterFavOrgView.as_view(), name='user_fav_org'),

    # 老师收藏
    url(r'^fav/teacher/$', UserCenterFavTeacherView.as_view(), name='user_fav_teacher'),

    # 头像修改
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),

    # 密码重设
    url(r'^resetpwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='send_email_code'),

    # 邮箱更改页面
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    ]

iMooc/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin
from iMooc.settings import MEDIA_ROOT

from users.views import LoginView, RegisterView, ActiveUserView, ForgetView, ResetView, ResetPwdView, HomeView,\
    LoginOutView

urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LoginOutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='active'),
    url(r'^forget/$', ForgetView.as_view(), name='forget'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name='reset'),
    url(r'^resetpwd/$', ResetPwdView.as_view(), name='resetpwd'),

    # 图片路径处理
    url(r'^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT}),
    # 静态文件夹 static 处理
    # url(r'^static/(?P<path>.*)/$', serve, {'document_root': STATIC_ROOT}),

    # 加载 organization url路由
    url(r'^org/', include('organization.urls', namespace='org')),

    # 加载 course url路由
    url(r'^course/', include('courses.urls', namespace='course')),

    # 用户信息
    url(r'^user/', include('users.urls', namespace='user')),
    # django ueditor 配置
    url(r'^ueditor/', include('DjangoUeditor.urls')),

]


# 配置全局404
handler404 = 'users.views.page_not_found'
# 500页面
handler500 = 'users.views.page_error'

apps/courses/models.py
# coding:utf-8
from datetime import datetime

from django.db import models

# Create your models here.
from DjangoUeditor.models import UEditorField

#  课程信息
from organization.models import CourseOrg, Teacher


class Course(models.Model):
    """
    课程信息
    """
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', null=True, blank=True)
    teacher = models.ForeignKey(Teacher, default='', verbose_name='课程老师', null=True, blank=True)
    name = models.CharField(max_length=20, verbose_name='课程名称')
    course_type = models.CharField(max_length=10, verbose_name='课程类别', default='', null=True, blank=True)
    desc = models.CharField(max_length=50, verbose_name='课程描述')
    detail = models.TextField(verbose_name='课程详情')
    difficulty = models.CharField(choices=(('low', '初级'), ('mid', '中级'), ('high', '高级')),
                                  max_length=4, verbose_name='学习难度')
    learn_times = models.IntegerField(default=0, verbose_name='学习时间(分钟)')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    like_numbers = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(max_length=200, verbose_name='描述图片', upload_to='courses/%Y/%m')
    click_numbers = models.IntegerField(default=0, verbose_name='点击数量')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播显示')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def get_lesson_nums(self):
        return self.lesson_set.all().count()

    # 在后台管理页面设置 get_lesson_nums 函数显示的别名
    get_lesson_nums.short_description = '章节数量'

    def relate_courses(self):
        return self.objects.filter(course_type=self.course_type).all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    # 轮播图课程，继承于上面的 Course
    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        proxy = True  # 不生成新的数据表


class Lesson(models.Model):
    """
    课程章节信息
    """
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=50, verbose_name='章节名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_lesson_videos(self):
        """
        获取该章节的所有视频
        :return: videos list
        """
        return self.videos_set.all()


class Videos(models.Model):
    """
    每章节的视频信息
    """
    lesson = models.ForeignKey(Lesson, verbose_name='章节名称')
    name = models.CharField(max_length=50, verbose_name='视频名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """
    右侧资源链接
    """
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=50, verbose_name='视频名称')
    download = models.FileField(max_length=100, upload_to='courses/resource/%Y/%m', verbose_name='课程资源')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
iMooc学习网
{% endblock %}
{% block my_js %}
     <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

{% block my_bread %}
{% endblock %}

{%  block my_content %}
<!--crumbs start-->
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{{banner.url}}">
                                        <img width="1200" height="478" src="{{ banner.image.url }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_home' %}">查看更多课程 ></a>
					</div>

					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' course.id %}">
                                            <img width="470" height="300" src="{{ course.image.url }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in part_of_courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ course.image.url }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}</h2>
                                    </a>
                                    <span class= " fl " >难度：<i class="key" >{{ course.get_difficulty_display }} </i></span>
                                    <span class="fr">学习人数：{{course.students}}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{course.course_org.name}}">{{course.course_org.name}}</span>
                                    <span class="star fr">{{ course.like_numbers }}</span>
                                </div>
                            </div>
                            {% endfor %}


					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in course_orgs %}
                            <li class="{% if forloop.counter|divisibleby:'5' %}five{% else %}{% endif %}">
                                <a href="{% url 'org:org_home' org.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ org.image.url }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                </a>
                            </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}


templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block org_css %}{% endblock %}
    {% block org_js %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			
      {% if request.user.is_authenticated %}
        <!--登录后跳转-->
        <div class="top">
            <div class="wp">
                <div class="fl"><p>服务电话：<b>9999999</b></p></div>
                    <div class="personal">
                        <dl class="user fr">
                            <dd>{{ request.user.username }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                            <dt><img width="20" height="20" src="{{ request.user.image.url }}"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="{{ request.user.image.url }}"/></dt>
                                <dd>
                                    <h2>{{ request.user.nick_name }}</h2>
                                    <p>{{ request.user.username }}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="{% url 'user:user_center' %}">进入个人中心</a>
                                <a class="fr" href="{% url 'logout' %}">退出</a>
                            </div>
                        </div>
                    </div>
                    </div>
        </div>
        {% else %}
        <div class="top">
            <div class="wp">
                <div class="fl"><p>服务电话：<b>9999999</b></p></div>
                    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
            </div>
        </div>
        {% endif %}

            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ org_courses.image.url }}"/>
                    <div class="head fl">
                        <h1>
                            {{ org_courses.name }}
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">4.9</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin
                         " data-favid="22" data-fav-type="1">
                         {% if has_fav %}已收藏{% else %}收藏{% endif %}
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'home' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block org_detail %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' org_courses.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' org_courses.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' org_courses.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teach' org_courses.id %}">机构讲师</a></li>
			</ul>
		</div>
    {% block org_right %}

    {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
{#</div>#}
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/favorite/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        }
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ org_courses.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: "/static/images",
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
</body>
</html>

templates/password_reset_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>密码重置</title>
</head>
<body>
<h1>密码重置链接失效</h1>
</body>
</html>

templates/send_email_successful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>密码重置</title>
</head>
<body>
<h1>邮件已经发送，请注意查收</h1>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}我的收藏- iMooc在线网{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'home' %}">首页</a>></li>
                <li><a href="{% url 'user:user_center' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:user_fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:user_fav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'user:user_fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in user_fav_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{course.name}}</h2></a>
                                <span class="fl">时长：<i class="key">{{course.learn_times}}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{course.course_org.name}}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}


templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- iMooc在线网{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'home' %}">首页</a>></li>
                <li><a href="{% url 'user:user_center' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'user:user_fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:user_fav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'user:user_fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in user_fav_orgs %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="org-detail-homepage.html">
                                    <img width="160" height="90" src="{{ org.image.url }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{org.name}}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{org.city}}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}


templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% block title %}我的课程- iMooc在线网{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'home' %}">首页</a>></li>
                <li><a href="{% url 'user:user_center' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block custom_right_content %}
 <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ user_course.course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' user_course.course.id %}"><h2>{{user_course.course.name}}</h2></a>
                                <span class="fl">课时：<i class="key">{{user_course.course.learn_times}}</i></span>
                                <span class="fr">学习人数：{{user_course.course.students}}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{user_course.course.course_org.name}}</span>
                                <span class="star fr  notlogin" data-favid="15">{{user_course.course.like_numbers}}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}


